name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          
      - name: Restore dependencies
          run: dotnet restore
          env:
            NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add GitHub Packages source
          run: dotnet nuget add source \
            --username Julia-Mamsheva \
            --password ${{ secrets.PACKAGES_TOKEN }} \
            --store-password-in-clear-text \
            --name github \
            "https://nuget.pkg.github.com/Julia-Mamsheva/index.json"     
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Run unit tests
        run: dotnet test --no-build --configuration Release --verbosity normal